### ISSUE TITLE
Issues installing with conda-forge but not pip

### ISSUE THREAD

**Issue by jjia1** [theislab/cellrank2_reproducibility#60]
When installing cellrank/cellrank2 using conda-forge, even following the directions from your repository with:
```
conda install -c conda-forge cellrank
```
I get an `ImportError .... : undefined symbol: H5Pget_fapl_direct:` error when trying `import cellrank as cr` in my Jupyter notebook.

However, if I install everything in pip, there's no issues at all. 

Thanks!

**Comment by WeilerP** [comment]
Sorry for spotting this only now, @jjia1. Can you please check with the latest versions, and if the problem persists, open an issue on the [CellRank repo](https://github.com/theislab/cellrank)?
